//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoupdate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentDirectory {
            get {
                return ((string)(this["CurrentDirectory"]));
            }
            set {
                this["CurrentDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kiemthefullfree.online/autoupdate/tintuc/")]
        public string LauncherUrl {
            get {
                return ((string)(this["LauncherUrl"]));
            }
            set {
                this["LauncherUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kiemthefullfree.online/autoupdate/hostfile/")]
        public string UpdateUrl {
            get {
                return ((string)(this["UpdateUrl"]));
            }
            set {
                this["UpdateUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kiemthefullfree.online/autoupdate/hostfile/version.xml")]
        public string VersionFileUrl {
            get {
                return ((string)(this["VersionFileUrl"]));
            }
            set {
                this["VersionFileUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("version.xml")]
        public string VersionFileName {
            get {
                return ((string)(this["VersionFileName"]));
            }
            set {
                this["VersionFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tmp")]
        public string TmpFolder {
            get {
                return ((string)(this["TmpFolder"]));
            }
            set {
                this["TmpFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config.ini")]
        public string ConfigFile {
            get {
                return ((string)(this["ConfigFile"]));
            }
            set {
                this["ConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5622")]
        public string GameServPort {
            get {
                return ((string)(this["GameServPort"]));
            }
            set {
                this["GameServPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5623")]
        public string DenialPort {
            get {
                return ((string)(this["DenialPort"]));
            }
            set {
                this["DenialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kiemthefullfree.online/autoupdate/hostfile/Autoupdate.exe")]
        public string AutoupdateFileUrl {
            get {
                return ((string)(this["AutoupdateFileUrl"]));
            }
            set {
                this["AutoupdateFileUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Autoupdate.exe")]
        public string AutoupdateFileName {
            get {
                return ((string)(this["AutoupdateFileName"]));
            }
            set {
                this["AutoupdateFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Autoupdate.ini")]
        public string AutoupdateINI {
            get {
                return ((string)(this["AutoupdateINI"]));
            }
            set {
                this["AutoupdateINI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Game.exe")]
        public string GameFile {
            get {
                return ((string)(this["GameFile"]));
            }
            set {
                this["GameFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vn.fon")]
        public string Suafont {
            get {
                return ((string)(this["Suafont"]));
            }
            set {
                this["Suafont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KYKeoxe\\KYKeoxe.exe")]
        public string AutoKyKx {
            get {
                return ((string)(this["AutoKyKx"]));
            }
            set {
                this["AutoKyKx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto\\AutoVLBS19_Free\\AutoVLBSFree.exe")]
        public string AutoTrainFile {
            get {
                return ((string)(this["AutoTrainFile"]));
            }
            set {
                this["AutoTrainFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VLBS_PK_12\\VLBS_PK.exe")]
        public string AutoPKFile {
            get {
                return ((string)(this["AutoPKFile"]));
            }
            set {
                this["AutoPKFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kiemthefullfree.online")]
        public string WebHome {
            get {
                return ((string)(this["WebHome"]));
            }
            set {
                this["WebHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kiemthefullfree.online/dang-ky/")]
        public string WebRegister {
            get {
                return ((string)(this["WebRegister"]));
            }
            set {
                this["WebRegister"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.facebook.com/kiemthefullfree")]
        public string WebFanPage {
            get {
                return ((string)(this["WebFanPage"]));
            }
            set {
                this["WebFanPage"] = value;
            }
        }
    }
}
